# Generated by Django 4.0.3 on 2022-05-14 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('companyname', models.TextField(null=True)),
                ('companydocs', models.FileField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(blank=True, null=True)),
                ('pitch', models.TextField(blank=True, null=True)),
                ('aadhar', models.FileField(null=True, upload_to='')),
                ('Pancard', models.ImageField(blank=True, null=True, upload_to='')),
                ('Voterid', models.ImageField(blank=True, null=True, upload_to='')),
                ('selfie', models.ImageField(null=True, upload_to='')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
