# Generated by Django 4.0.3 on 2022-05-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gettingstarted', '0003_alter_verification_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify', to=settings.AUTH_USER_MODEL),
        ),
    ]
