# Generated by Django 4.0.3 on 2022-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettingstarted', '0004_alter_verification_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='Pancard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='Voterid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='aadhar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='companydocs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='companyname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='selfie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
