# Generated by Django 4.0.3 on 2022-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettingstarted', '0005_alter_verification_pancard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='companyname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
