# Generated by Django 4.0.3 on 2022-05-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettingstarted', '0002_alter_verification_pancard_and_more'),
        ('gettingstarted', '0006_alter_verification_companyname_and_more'),
    ]

    operations = [
    ]
