# Generated by Django 4.0.3 on 2022-05-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('name_own', models.CharField(blank=True, max_length=255, null=True)),
                ('companyname', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('pitch', models.TextField(blank=True, null=True)),
                ('valuation', models.CharField(blank=True, max_length=225, null=True)),
                ('sales', models.CharField(blank=True, max_length=225, null=True)),
                ('margin', models.CharField(blank=True, max_length=225, null=True)),
                ('profit_month', models.CharField(blank=True, max_length=225, null=True)),
                ('profit_year', models.CharField(blank=True, max_length=225, null=True)),
                ('owership', models.IntegerField(blank=True, null=True)),
                ('dil_equity', models.IntegerField(blank=True, null=True)),
                ('ls_equity_members', models.TextField(blank=True, null=True)),
                ('open_to_investors', models.BooleanField(default=False)),
                ('open_to_partners', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
