# Generated by Django 4.0.4 on 2022-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_owner_alter_portfolio_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='comp_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
