# Generated by Django 4.0.3 on 2022-05-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_comp_contact_portfolio_comp_email_and_more'),
        ('portfolio', '0004_portfolio_open_to_business'),
    ]

    operations = [
    ]
