# Generated by Django 4.0.3 on 2022-05-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_merge_20220515_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='open_to_business',
        ),
    ]
