# Generated by Django 4.0.3 on 2022-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_portfolio_open_to_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
