# Generated by Django 4.0.3 on 2022-05-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_comp_contact'),
        ('portfolio', '0009_alter_portfolio_owner'),
    ]

    operations = [
    ]
