# Generated by Django 4.0.3 on 2022-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleuser', '0002_alter_college_student_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration_manage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college_student',
            name='add_previous_education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='college_student',
            name='collage_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college_student',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college_student',
            name='specification_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuration_manage',
            name='add_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuration_manage',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employed',
            name='add_previous_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employed',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employed',
            name='position_in_company',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='school_student',
            name='academy_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school_student',
            name='current_qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school_student',
            name='qualification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
