# Generated by Django 4.0.3 on 2022-05-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('singleuser', '0003_configuration_manage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_student',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuration_manage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration_manage',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employed',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employed', to=settings.AUTH_USER_MODEL),
        ),
    ]
